DevCon0/storyboard

- server/main.go
- server/schema.go
> basic schema file for mongodb

- client/app.js
- client/css/style.css
- client/index.html
- client/services/storyStorage.js
- client/splash/splash.html
- client/splash/splash.js
Added that cool overlay effect.
> Few changes to the front end and CSS

- client/app.js
- client/css/style.css
- client/dashboard/dashboard.html
- client/dashboard/dashboard.js
- client/index.html
- client/navBar/navBar.html
- client/navBar/navBar.js
- client/services/authServices.js
- client/services/storyStorage.js
- client/splash/splash.html
Changes to my files.  Lots of front end setup.  Should have a working nav bar with functional sign up (and probably sign in).
> Dashboard and NavBar functionality and some small CSS tweeks

- client/css/style.css
- client/services/authServices.js
- client/services/storyStorage.js
- client/splash/splash.html
Just some CSS to center the splash page.
> Center image on splash page

- client/createStory/createStory.html
- client/navBar/navBar.html
Add it to the Nav bar and changed the message when you switch views.
> Added Create Story to Nav Bar

- client/auth/auth.js
- client/auth/signin.html
- client/auth/signup.html
- client/css/style.css
Change Login Error message and color
> Change Login Error message and color

- client/css/style.css
- client/splash/splash.html
Borders on Top 3 and overlay p tag.
> Small CSS changes

- client/css/style.css
- client/dashboard/dashboard.html
- client/dashboard/dashboard.js
- client/services/storyStorage.js
Added the service for getting a user library for the dashboard.  It's
commented out and hard coded data is currently present for testing.  And
of course some CSS changes.
> Wrote User Library Service for the Dashboard

- client/css/style.css
- client/dashboard/dashboard.html
- client/services/storyStorage.js
> CSS on Dashboard

- client/createStory/createStory.html
- client/createStory/createStory.js
- client/css/style.css
- client/index.html
- client/services/storyStateMachine.js
- client/singleStory/singleStory.html
* Implemented the 'create story' page and 'create story' controller.
* Loading the youtube API script in index.html because we will need it in at least two views. Also, I'm registering the onYoutubeReady callback immediately above it in a script tag and also creating a window variable that we can check before using Youtube.
The user can paste Youtube URLs into the input form for each frame of the story.  The user can specify a start and stop time for each video.  The user may click "Preview Frame" which will open a preview youtube player that the user may click to play their snippet of video.  After the user fills out all fields, a "Save Your Story" button will appear.  The user may click this button and we will create a story object based on their input but we will not send it up to the …
> 'Create Story' page with no connection to server

- client/app.js
- client/css/style.css
- client/index.html
- client/navBar/navBar.html
- client/profile/profile.html
- client/profile/profile.js
- client/services/storyStorage.js
- client/services/userServices.js
- client/singleStory/singleStory.js
View Controller Factory and services.
> Adding in Profile

- client/services/storyStorage.js
- client/singleStory/singleStory.js
Adding the hard coded ID and configured the response to pass to the storyStorageService properly.
> Small Modificaiton to singleStory controller

- client/createStory/createStory.html
- client/createStory/createStory.js
- client/services/storyStorage.js
* Pulling in StoryStorage to the create story controller.
* Adding title, description, username and author to the story to save.
* Parsing start and end time as integers before passing to server.
> Saving a story to the server

- client/createStory/createStory.js
- client/services/storyStorage.js
Added Token to header of saveStory function
> Added Token to header of saveStory function

- client/dashboard/dashboard.js
- client/services/storyStorage.js
- client/splash/splash.js
Getting rid of some hard coded data.
> Removing some Data

- client/createStory/createStory.html
Keeps alot of errors from happening and forces the destroyFrames function to run.
> Preview Modal won't close when clicked off

- client/services/authServices.js
Adding token to header of logout service API Call
> Adding token to header of logout service API Call

- client/app.js
- client/createStory/createStory.html
- client/createStory/createStory.js
- client/createStory/onUrlErrorDirective.js
- client/css/style.css
- client/index.html
* Reorganized create story page for compactness. 
* Allow preview of thumbnail URL.
* Created directive to detect broken thumbnail links.
> Add thumbnail URL ability for create story page.

- client/app.js
- client/services/storyStorage.js
- client/singleStory/singleStory.js
- client/splash/splash.html
- client/splash/splash.js
Got the front end for the splash page and the view story on click working.
> Front End Splash page and view Story

- client/singleStory/singleStory.js
> Remove some console logs.

- client/navBar/navBar.js
- client/services/authServices.js
The token is now passed into the logout request and removed from the database.
> Tied in logout to the back end

- client/createStory/createStory.html
Fixes the bug that causes it to show up on the next page.
> Add dismiss to the Create Story modal on save button click 

- client/css/style.css
- client/index.html
- client/splash/splash.html
* Most times, thumbnails did not occupy the space of the story square/div.
* Also the story title sometimes would be cut off.
* Also, removing a reference to userServices.js, which was deleted in a previous commit.
> Smoothing out some styling issues with the top 3 splash page.

- client/dashboard/dashboard.js
- client/services/storyStorage.js
> Delete Story button on Dashboard

- client/app.js
- client/createStory/createStory.js
- client/dashboard/dashboard.js
- client/services/storyStorage.js
Edit Story Functionality Added
> Edit Story Functionality

- client/createStory/createStory.js
Got rid of a few things (modal controller and view) and refactored the createStory controller to include a variable for the sessiontoken and a function to reassemble the URL from the id.
> Clean up for the createStory controller

- server/src/handler.go
- server/src/main_test.go
- server/src/schema.go
- server/src/story.go
- server/src/user.go
Token is now added to the database only after user document has been
created.
> Fixed signup.

- bower.json
- client/app.js
- client/createStory/createStory.html
- client/createStory/createStory.js
- client/css/style.css
- client/index.html
* New bower dependencies for Polymer paper elements, plus ng-polymer-elements, which allows ng-model to work with paper elements.
* Added dropdown menu for each frame.  Select media type to proceed.
* User can select image URL and image duration.  User can also preview image.
* createStory.js - adding defaults in save/edit cases for the new image scope variables.
* createStory.js - moved the variables outside the if(wasPassed) block if they have the same value in both the if case and the else case.
* Added TODOs for assigning the image scope variables if a story is passed in for editing.
* Gave defaults for pre-populate inputs for image scope variables.
* createStory.js - previewImageFrame() allows the image div to ng-show so the user may preview his image.
> Adding ability to select media type when creating a frame in story

- client/index.html
- client/services/storyStateMachine.js
* Instead of depending on internal variables that I discovered on my own, I am now using the public API entry point "getIframe()" which shouldn't be subject to changes. 
* Also, adjusting a line break issue in index.html.
> Fixing issue with video re-cue breaking due to internal changes in Youtube JS object player.

- client/createStory/createStory.js
create or edit video defaults to 0 start time, no longer checked as required field
> bug fix for save edit start time

- client/css/style.css
- client/singleStory/singleStory.html
> CSS for Single Story View

- client/createStory/createStory.html
Seems it's a bootstrap thing, and there's a work around.
> Bug fix for Modal not going away

- client/css/style.css
- client/services/imagePlayer.js
* Also, fixed some offset indentation in style.css.
* Also, Sublime cleaned up some trailing whitespace.
> Moved the inline CSS out of imagePlayer.js and into a class in style.css

- client/css/style.css
- client/services/storyStateMachine.js
- client/singleStory/singleStory.html
- client/singleStory/singleStory.js
Change to Single Story CSS and information/replay revealer
> Change to Single Story CSS and information/replay revealer

- client/app.js
- client/createStory/createStory.html
- client/createStory/createStory.js
- client/css/style.css
- client/index.html
- client/services/storyStateMachine.js
- client/services/textToSpeechPlayer.js
- client/services/videoPlayer.js
- server/src/schema.go
* Also, fixed bug when a video pauses and then ends, that results in two callback calls: once for 'paused' and once for 'ended'.  We now have a boolean to track, in general, when a video stops *once* and then we only call its endPlayback Callback once.
> Added text-to-speech media type for frames.

- client/services/textToSpeechPlayer.js
* Added fall-back voices to try if our first choice speech synthesis voice is not available in the user's browser.
> Added fall-back voices for browsers with limited Speech Synthesis voice library.

- bower.json
- client/createStory/createStory.html
- client/createStory/createStory.js
- client/css/style.css
- client/index.html
- client/singleStory/singleStory.html
* Removed lots of polymer paper-based UI elements and the accompanying CSS. 
* Fixed importing of a story's media types when editing. 
* Added the word 'replay' to replay button. 
* Removed almost all paper dependencies from bower file and index.html
* Styling media select elements and changing text to 'Select Media'
> Create Story page - removed lots of polymer paper elements

- server/src/handler.go
- server/src/main.go
- server/src/story.go
- server/src/user.go
* Renamed library to getLibrary. 
* Renamed showCaseRandom to getShowCaseRandom and now returning 16. 
* Rewrote intSlcContains to contains() on an IntSlice type. 
* Fixed indentation for nested switch structures. 
* Removed commented out code referring to mithril. 
* Rewrote verifyToken function to be more generic and take a token as input. 
* Created a getUserToken helper function.
> Backend refactoring

- client/services/storyStateMachine.js
- client/singleStory/singleStory.css
- client/singleStory/singleStory.html
- client/singleStory/singleStory.js
Adding logic for loading spinner display and remove when first player (not audio track) is ready.
> Adding logic for loading display and remove when first player is ready

- client/services/storyStateMachine.js
* Making the storyStateMachine's obj properties more explicit.
* Calling _createPlayer before _determineReadyCallback so we have the player object we need to bind to the restart function.
* In endStory(), I am explicitly emptying/resetting storyStateMachine variables.
* Saving the restart function in _determineReadyCallback b/c we were already doing the logic with hasSoundtrack there.
> Refactoring how we know which function to call to restart the story.

- client/createStory/createStory.html
- client/css/style.css
Buttons all the same size and color on single Story Page
> Buttons all the same size and color on single Story Page

- client/createStory/createStory.html
- client/createStory/createStory.js
Added a drop down field for background audio.
Only shows for video frames.
Only shows when 'Add Audio Track' is clicked.
Hides when 'Remove Audio Track' is clicked.
Added single act preview function, which is separate from the video preview function.
Background audio is played upon story preview.
> Background audio player creation

- client/auth/auth.js
- client/createStory/createStory.js
* There are still a ton of linting errors but a journey of a thousand miles begins with a single step.
> First pass at removing linting errors.

- client/app.js
- client/dashboard/dashboard.js
- client/errorPage/errorPage.html
- client/errorPage/errorPage.js
- client/index.html
- client/services/storyStorage.js
- client/singleStory/singleStory.js
Added ErrorPage state/controller/html and created a Test folder and file
for eventual tests
> Added ErrorPage state/controller/html and created a Test folder and file for eventual tests

- server/serve
- server/src/main.go
- server/test-run
For us, we can just add the mongodb url in a file: `server/db-url`
> Removed hard-coded mongodb url

- client/createStory/createStory.html
- client/createStory/createStory.js
"Preview" button ng-hides when a video is playing.
The readyCallback for the video hides the spinner.
The endCallback for the video re-shows the preview button.
> Hide "Preview" button during previews. Show spinners while videos are loading.

- client/css/style.css
and do not extend outside of the container
> Single-frame image previews centered vertically and horizontally

- client/createStory/createStory.html
- client/createStory/createStory.js
- client/services/textToSpeechPlayer.js
This is gross, but will lead to a parallel re-factor of all the create.js grossness.
> add remove act audio track works like story soundtrack now

- client/test/mockYoutubePlayer.js
- client/test/videoPlayerTest.js
- karma.conf.js
* VideoPlayer should only call EndPlaybackCallback once after the youtube video ends.
* MockYoutubePlayer simulates events by calling the state change listener callback and passing in the Youtube event constants.
> Created a MockYoutubePlayer and added test for EndPlaybackCallback.

- Gruntfile.js
- client/dashboard/dashboard.js
- client/errorPage/errorPage.js
- client/navBar/navBar.js
- client/services/authServices.js
- client/services/player.js
- client/services/storyStateMachine.js
- client/services/storyStorage.js
- client/services/textToSpeechPlayer.js
- client/services/videoPlayer.js
- client/splash/splash.js
Lint Pass 1 - i.e. adding and removing semicolons
> Lint Pass 1 - i.e. adding and removing semicolons

- Gruntfile.js
- package.json
Small pull request to introduce min/uglify with ngAnnotate and uglify
> Small pull request to introduce min/uglify with ngAnnotate and uglify

- client/auth/auth.js
- client/dashboard/dashboard.js
- client/services/storyStateMachine.js
- client/services/videoPlayer.js
- client/singleStory/singleStory.js
Remove Console Logs and vote functions
> Remove Console Logs and vote functions

- client/css/style.css
- client/dashboard/dashboard.html
- client/index.html
- client/navBar/navBar.html
- client/navBar/navBar.js
- client/services/pageInfo.js
- client/singleStory/singleStory.js
- client/splash/splash.html
- client/splash/splash.js
Added a PageInfo factory which shares info between controllers. Right now, it just shares page 'title' information.
Added the page title to the navbar.
Removed other, now-unneeded pages titles (dashboard, splash, and profile pages).
Changed navbar background color.
Navbar controller watches for changes to the title in the PageInfo factory.
In this request, other controllers do not change PageInfo's 'title' property. That will be another pull request.
> New page title

- client/services/storyStateMachine.js
- client/test/storyStateMachineTest.js
* Also, removed a console.log that was cluttering the unit testing results output.
> Adding unit testing for Story State Machine

- client/createStory/createStory.html
- client/createStory/createStory.js
This should lead to more lines cut from createStory.js, and a possible FrameFactory service for the whole app.
> refactor first pass on edit story

- client/app.js
- client/createStory/createStory.js
- client/library/library.html
- client/library/library.js
Before, users had to click the edit button in the library in order to edit a story, and if they refreshed the editStory page, the story data would reset to the empty defaults. This pull request lets them go to 'editStory/storyId' so that they can refresh the page if they want to reset back to the saved data for the story.
> editStory state has the storyId in the url

- client/index.html
- client/test/createStoryTest.js
- karma.conf.js
* Remove script include of old dependency (ng-polymer-elements).  We had deleted it from bower.json but we didn't remove the script include in index.html
* Changed karma.conf.js to include the full angular.js instead of angular.min.js to facilitate debugging when you want to step into angular code.
* Included angular UI Router and angular Local Storage in karma.conf.js so I can load those dependencies when testing the createStory controller in the karma environment.
> Initial unit testing framework for createStory controller

- client/createStory/createStory.js
- client/navBar/navBar.js
* Also, renaming constants to STR instead of LINK b/c they are more strings than links.  
* Removing some break statements because they are unreachable due to the preceding return statements.
* Removing the usage of "const" keyword b/c it is only available in ES6.
> More fixes from jshint suggestions.

- Gruntfile.js
- client/navBar/navBar.js
- client/services/textToSpeechPlayer.js
* Moved function definition outside of FOR loop. 
* Added a missing semicolon.
* My editor removed some trailing spaces in the grunt file.
> Fixes prompted by jshint
